"""Changed card_number from Integer to String

Revision ID: 14508d17a06d
Revises: d98b6078e70c
Create Date: 2024-03-15 17:39:04.035001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14508d17a06d'
down_revision = 'd98b6078e70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_detail', schema=None) as batch_op:
        batch_op.alter_column('card_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_detail', schema=None) as batch_op:
        batch_op.alter_column('card_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
