"""Create Tables

Revision ID: 7d939432c000
Revises: 
Create Date: 2024-01-24 08:08:53.929796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d939432c000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('newsletter_mails',
    sa.Column('newsletter_mails_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('newsletter_mails_id')
    )
    op.create_table('owners',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('accommodations',
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('preview', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], name=op.f('fk_accommodations_owner_id_owners')),
    sa.PrimaryKeyConstraint('accommodation_id')
    )
    op.create_table('customer_profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('dp_url', sa.String(), nullable=True),
    sa.Column('backup_mail', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_customer_profile_customer_id_customers')),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('payment_detail',
    sa.Column('payment_detail_id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(), nullable=True),
    sa.Column('card_number', sa.Integer(), nullable=True),
    sa.Column('CVV', sa.Integer(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_payment_detail_customer_id_customers')),
    sa.PrimaryKeyConstraint('payment_detail_id')
    )
    op.create_table('vacations',
    sa.Column('vacation_id', sa.Integer(), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('preview', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], name=op.f('fk_vacations_owner_id_owners')),
    sa.PrimaryKeyConstraint('vacation_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('booked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vacation_id', sa.Integer(), nullable=True),
    sa.Column('accommodation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.accommodation_id'], name=op.f('fk_bookings_accommodation_id_accommodations')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_bookings_customer_id_customers')),
    sa.ForeignKeyConstraint(['vacation_id'], ['vacations.vacation_id'], name=op.f('fk_bookings_vacation_id_vacations')),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vacation_id', sa.Integer(), nullable=True),
    sa.Column('accommodation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.accommodation_id'], name=op.f('fk_reviews_accommodation_id_accommodations')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_reviews_customer_id_customers')),
    sa.ForeignKeyConstraint(['vacation_id'], ['vacations.vacation_id'], name=op.f('fk_reviews_vacation_id_vacations')),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('bookings')
    op.drop_table('vacations')
    op.drop_table('payment_detail')
    op.drop_table('customer_profile')
    op.drop_table('accommodations')
    op.drop_table('owners')
    op.drop_table('newsletter_mails')
    op.drop_table('customers')
    # ### end Alembic commands ###
